Fix analog tool on .gz files
It seems `gzip` by default opens files in binary mode, which is why the parser then breaks when processing the extracted data:  ```
❯ wer --verbose-errors /long/path/redacted/for/brevity/search.log.1.gz
/u/mgunz/tools/rasr_no_tf/src/Tools/Analog/analog:14: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import glob, imp, os, sys
Can not load PyQt. Gui will not work.
failed to load plug-in "ov": No module named 'sequitur_'
                              |                   word errors                    |  time 
file/subcorpus                | seg    del    ins    sub    errors words    wer  |  rtf  
------------------------------+--------------------------------------------------+-------
/long/path/redacted/for/brevity/search.log.1.gz FAILED
Traceback (most recent call last):
  File "/work/tools/users/raissi/shared/mgunz/rasr_no_tf/src/Tools/Analog/analog_util/analog.py", line 353, in processFiles
    self.parser.parseFile(fname, segments)
  File "/work/tools/users/raissi/shared/mgunz/rasr_no_tf/src/Tools/Analog/analog_util/parser.py", line 418, in parseFile
    super(LogFileParser, self).parseFile(fname)
  File "/work/tools/users/raissi/shared/mgunz/rasr_no_tf/src/Tools/Analog/analog_util/parser.py", line 30, in parseFile
    if data.startswith('<?xml'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
/long/path/redacted/for/brevity/search.log.1.gz
------------------------------+--------------------------------------------------+-------
```

By setting the mode to `rt` explicitly, we get the gzip module to extract text.

Tested under python 3.10.